---
title: "Coverage plot"
author: "Panu Erästö (partially based on code by Milla Juntunen and Mikko Arvas)"
date: "`r Sys.time()`"
output:
  html_document:
    toc: true
    theme: united
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(sf)
library(mapsFinland)
library(ggpubr)
library(readxl)
```



# Coverage map from simulations

```{r}

# Load 1x1km euref-coordinates together with variable continent
df_continent <- read.csv("../data/1x1km_grid.csv", sep =";", header = TRUE, colClasses = c("numeric", "numeric", "numeric","numeric"))
df_continent$trauma_saatto_enn_sum=100 # This just defines the drawing colour 

# Load the performance data from the simulations (CHANGE this to different files **BDC_10**,...**BCD_25**)
load("../BCD_15_locations.RData")

# Take the union of the INDICES of handled locations over the simulations
temp<- Reduce(union, lapply(result_list, function(x) x$handled_event_locations))

# Load the file containing the corresponding temporary coordinates
ennusteet=read.csv(file = "../data/Trauma_ennusteet_1x1.csv",header = TRUE,sep=";",dec=",")
# And attach the temporary coordinates from $nro to the indices 
apu <- list() # 
apu$nro=ennusteet$nro[temp]

# And finally combine the temporary coordinates to real (euref-) coordinates
df_traumascomb <- merge(x=apu, y = df_continent, by = "nro")

#######

#leave out islands
df_traumas <- filter(df_traumascomb, df_traumascomb$manner == 1)
#df_traumas

#store zeros as we want them to be white 
zeros <- filter(df_traumas, df_traumas$trauma_saatto_enn_sum == 0)

#filter out zeros to make log transfromation work
df_traumas <- filter(df_traumas, df_traumas$trauma_saatto_enn_sum > 0)
#Original predictions are event per year, make them per 10 years
traumas <- df_traumas$trauma_saatto_enn_sum*10 

traumas_map <- maakunta2019 %>%
  st_transform(st_crs(3067)) %>%
  ggplot() + 
  geom_sf() +
  geom_point(data = zeros, aes(euref_x, euref_y), color = "white",  size = 0.000001) +
  geom_point(data = df_traumas, aes(euref_x, euref_y, color = traumas), size = 0.000001) +
  scale_color_gradient(low  = "white", high = "blue", trans = "log10")+#, breaks = c(0.01, 0.1, 1, 10))+
  #ggtitle("Predicted traumas in 10 years") + 
  labs(x = "Longitude", y = "Latitude", color = "Traumas per 25 km²") +
theme(legend.position='bottom',
        legend.text = element_text(size=10),
        legend.title.position = "bottom"
        )
traumas_map
```






